# Generated by Django 3.0.8 on 2020-12-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201227_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='business',
            new_name='name',
        ),
    ]
