# Generated by Django 3.0.8 on 2020-12-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsappnum',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
