# Generated by Django 3.0.8 on 2020-12-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_whatsappnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ighandle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitterhandle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtubepage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
